# NAME: Marcus Pearce, Ryan Lam
# EMAIL: marcuspearce7@g.ucla.edu, ryan.lam53@gmail.com
# ID: 305115848, 705124474

# CS 111 Project 3b

default: lab3b.py
	rm -f lab3b
	ln -s lab3b.py lab3b
	chmod +x lab3b

dist: default
	tar -czvf lab3b-705124474.tar.gz lab3b.py Makefile README

clean: 
	rm -f lab3b lab3b-705124474.tar.gz