# NAME: Marcus Pearce, Ryan Lam
# EMAIL: marcuspearce7@g.ucla.edu, ryan.lam53@gmail.com
# ID: 305115848, 705124474

# CS 111 Project 3a

.SILENT:

default:
	gcc -g -Wall -Wextra lab3a.c -o lab3a

dist:
	tar -czvf lab3a-305115848.tar.gz lab3a.c ext2_fs.h README Makefile

clean:
	rm -f lab3a lab3a-305115848.tar.gz